### ISSUE TITLE
FAS 1002 - Quiz #6 

### ISSUE THREAD

**Issue by CynthiaBH** [CynthiaBH/github-slideshow#4]
@SamGuay
![cat](https://user-images.githubusercontent.com/90490984/136875132-e347def8-ad3e-4f49-8ec6-5d0c36d4486f.gif)
-Cynthia Bello-

**Comment by SamGuay** [comment]
A real coder! :rocket: ! 
Excellent gif + meme dans ta [présentation](https://cynthiabh.github.io/github-slideshow/#/)!
